# Generated by Django 4.1.8 on 2023-04-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResults',
        ),
    ]
