# Generated by Django 4.1.8 on 2023-04-26 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_searchresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='url',
        ),
        migrations.AddField(
            model_name='history',
            name='query',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
