# Generated by Django 4.1.8 on 2023-04-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_history_url_history_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
