# Generated by Django 4.1.7 on 2023-03-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.CharField(max_length=100),
        ),
    ]
